# Generated by Django 4.1.3 on 2022-12-04 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comunas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comuna', models.CharField(choices=[['Cerrillos', 'Cerrillos'], ['Cerro Navia', 'Cerro Navia'], ['Conchalí', 'Conchalí'], ['El Bosque', 'El Bosque'], ['Estación Central', 'Estación Central'], ['Huechuraba', 'Huechuraba'], ['Independencia', 'Independencia'], ['Cisterna', 'Cisterna'], ['La Florida', 'La Florida'], ['La Granja', 'La Granja'], ['La Pintana', 'La Pintana'], ['La Reina', 'La Reina'], ['Las Condes', 'Las Condes'], ['Lo Barnechea', 'Lo Barnechea'], ['Lo Espejo', 'Lo Espejo'], ['Lo Prado', 'Lo Prado'], ['Macul', 'Macul'], ['Maipú', 'Maipú'], ['Ñuñoa', 'Ñuñoa'], ['Pedro Aguirre Cerda', 'Pedro Aguirre Cerda'], ['Peñalolén', 'Peñalolén'], ['Providencia', 'Providencia'], ['Pudahuel', 'Pudahuel'], ['Quilicura', 'Quilicura'], ['Quinta Normal', 'Quinta Normal'], ['Recoleta', 'Recoleta'], ['Renca', 'Renca'], ['Santiago', 'Santiago'], ['San Joaquín', 'San Joaquín'], ['San Miguel', 'San Miguel'], ['San Ramón', 'San Ramón'], ['Vitacura', 'Vitacura'], ['Puente Alto', 'Puente Alto'], ['Pirque', 'Pirque'], ['San José de Maipo', 'San José de Maipo'], ['Colina', 'Colina'], ['Lampa', 'Lampa'], ['Tiltil', 'Tiltil'], ['San Bernardo', 'San Bernardo'], ['Buin', 'Buin'], ['Calera de Tango', 'Calera de Tango'], ['Paine', 'Paine'], ['Melipilla', 'Melipilla'], ['Alhué', 'Alhué'], ['Curacaví', 'Curacaví'], ['María Pinto', 'María Pinto'], ['San Pedro', 'San Pedro'], ['Talagante', 'Talagante'], ['El Monte', 'El Monte'], ['Isla de Maipo', 'Isla de Maipo'], ['Padre Hurtado', 'Padre Hurtado'], ['Peñaflor', 'Peñaflor']], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CuentaRecolector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rut_Empresa', models.CharField(max_length=100, unique=True)),
                ('Nombre', models.CharField(max_length=50)),
                ('Apellido', models.CharField(max_length=50)),
                ('Correo_electronico', models.EmailField(max_length=50)),
                ('Telefono', models.CharField(max_length=100)),
                ('Direccion', models.CharField(max_length=100)),
                ('Nombre_de_empresa', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Regiones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Region', models.CharField(choices=[['Region Metropolitana', 'Region Metropolitana']], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CuentaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rut', models.CharField(max_length=100, unique=True)),
                ('Nombre', models.CharField(max_length=50)),
                ('Apellido', models.CharField(max_length=50)),
                ('Correo_electronico', models.EmailField(max_length=50)),
                ('Telefono', models.CharField(max_length=100)),
                ('Direccion', models.CharField(max_length=100)),
                ('Comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RecismartAPP.comunas')),
                ('Region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RecismartAPP.regiones')),
            ],
        ),
    ]
