# Generated by Django 4.1.3 on 2022-12-11 19:29

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo_de_publicacion', models.CharField(max_length=100, unique=True)),
                ('Descripcion', models.TextField(max_length=500)),
                ('Comuna', models.CharField(blank=True, choices=[['Cerrillos', 'Cerrillos'], ['Cerro Navia', 'Cerro Navia'], ['Conchalí', 'Conchalí'], ['El Bosque', 'El Bosque'], ['Estación Central', 'Estación Central'], ['Huechuraba', 'Huechuraba'], ['Independencia', 'Independencia'], ['Cisterna', 'Cisterna'], ['La Florida', 'La Florida'], ['La Granja', 'La Granja'], ['La Pintana', 'La Pintana'], ['La Reina', 'La Reina'], ['Las Condes', 'Las Condes'], ['Lo Barnechea', 'Lo Barnechea'], ['Lo Espejo', 'Lo Espejo'], ['Lo Prado', 'Lo Prado'], ['Macul', 'Macul'], ['Maipú', 'Maipú'], ['Ñuñoa', 'Ñuñoa'], ['Pedro Aguirre Cerda', 'Pedro Aguirre Cerda'], ['Peñalolén', 'Peñalolén'], ['Providencia', 'Providencia'], ['Pudahuel', 'Pudahuel'], ['Quilicura', 'Quilicura'], ['Quinta Normal', 'Quinta Normal'], ['Recoleta', 'Recoleta'], ['Renca', 'Renca'], ['Santiago', 'Santiago'], ['San Joaquín', 'San Joaquín'], ['San Miguel', 'San Miguel'], ['San Ramón', 'San Ramón'], ['Vitacura', 'Vitacura'], ['Puente Alto', 'Puente Alto'], ['Pirque', 'Pirque'], ['San José de Maipo', 'San José de Maipo'], ['Colina', 'Colina'], ['Lampa', 'Lampa'], ['Tiltil', 'Tiltil'], ['San Bernardo', 'San Bernardo'], ['Buin', 'Buin'], ['Calera de Tango', 'Calera de Tango'], ['Paine', 'Paine'], ['Melipilla', 'Melipilla'], ['Alhué', 'Alhué'], ['Curacaví', 'Curacaví'], ['María Pinto', 'María Pinto'], ['San Pedro', 'San Pedro'], ['Talagante', 'Talagante'], ['El Monte', 'El Monte'], ['Isla de Maipo', 'Isla de Maipo'], ['Padre Hurtado', 'Padre Hurtado'], ['Peñaflor', 'Peñaflor']], max_length=100, null=True)),
                ('Region', models.CharField(blank=True, choices=[['Region Metropolitana', 'Region Metropolitana']], max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CuentaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('Perfil_usuario', models.CharField(choices=[['Administrador', 'Administrador'], ['Usuario', 'Usuario'], ['Recolector', 'Recolector'], ['Invitado', 'Invitado']], default='Usuario', max_length=100)),
                ('Rut', models.CharField(max_length=100, unique=True)),
                ('Rut_Empresa', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('Nombre_de_empresa', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('Nombre', models.CharField(max_length=50)),
                ('Apellido', models.CharField(max_length=50)),
                ('Telefono', models.CharField(max_length=100)),
                ('Correo', models.EmailField(max_length=100, unique=True)),
                ('Direccion', models.CharField(max_length=100)),
                ('Comuna', models.CharField(choices=[['Cerrillos', 'Cerrillos'], ['Cerro Navia', 'Cerro Navia'], ['Conchalí', 'Conchalí'], ['El Bosque', 'El Bosque'], ['Estación Central', 'Estación Central'], ['Huechuraba', 'Huechuraba'], ['Independencia', 'Independencia'], ['Cisterna', 'Cisterna'], ['La Florida', 'La Florida'], ['La Granja', 'La Granja'], ['La Pintana', 'La Pintana'], ['La Reina', 'La Reina'], ['Las Condes', 'Las Condes'], ['Lo Barnechea', 'Lo Barnechea'], ['Lo Espejo', 'Lo Espejo'], ['Lo Prado', 'Lo Prado'], ['Macul', 'Macul'], ['Maipú', 'Maipú'], ['Ñuñoa', 'Ñuñoa'], ['Pedro Aguirre Cerda', 'Pedro Aguirre Cerda'], ['Peñalolén', 'Peñalolén'], ['Providencia', 'Providencia'], ['Pudahuel', 'Pudahuel'], ['Quilicura', 'Quilicura'], ['Quinta Normal', 'Quinta Normal'], ['Recoleta', 'Recoleta'], ['Renca', 'Renca'], ['Santiago', 'Santiago'], ['San Joaquín', 'San Joaquín'], ['San Miguel', 'San Miguel'], ['San Ramón', 'San Ramón'], ['Vitacura', 'Vitacura'], ['Puente Alto', 'Puente Alto'], ['Pirque', 'Pirque'], ['San José de Maipo', 'San José de Maipo'], ['Colina', 'Colina'], ['Lampa', 'Lampa'], ['Tiltil', 'Tiltil'], ['San Bernardo', 'San Bernardo'], ['Buin', 'Buin'], ['Calera de Tango', 'Calera de Tango'], ['Paine', 'Paine'], ['Melipilla', 'Melipilla'], ['Alhué', 'Alhué'], ['Curacaví', 'Curacaví'], ['María Pinto', 'María Pinto'], ['San Pedro', 'San Pedro'], ['Talagante', 'Talagante'], ['El Monte', 'El Monte'], ['Isla de Maipo', 'Isla de Maipo'], ['Padre Hurtado', 'Padre Hurtado'], ['Peñaflor', 'Peñaflor']], max_length=100)),
                ('Region', models.CharField(choices=[['Region Metropolitana', 'Region Metropolitana']], max_length=100)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
