# Generated by Django 4.1.3 on 2022-12-04 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RecismartAPP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo_de_publicacion', models.CharField(max_length=100, unique=True)),
                ('Descripcion', models.CharField(max_length=300)),
                ('Comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RecismartAPP.comunas')),
                ('Region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RecismartAPP.regiones')),
            ],
        ),
    ]
