# Generated by Django 4.1.3 on 2022-12-11 20:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecismartAPP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroaviso',
            name='Fecha_publicacion',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 11, 20, 5, 7, 421447, tzinfo=datetime.timezone.utc)),
        ),
    ]
