# Generated by Django 4.1.4 on 2022-12-09 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecismartAPP', '0002_registroaviso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentarecolector',
            name='Correo_electronico',
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='cuentausuario',
            name='Correo_electronico',
            field=models.EmailField(max_length=50, unique=True),
        ),
    ]
