# Generated by Django 4.1.4 on 2022-12-09 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecismartAPP', '0003_alter_cuentarecolector_correo_electronico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroaviso',
            name='imagen',
            field=models.ImageField(null=True, upload_to='publicacion'),
        ),
    ]
