# Generated by Django 4.1.4 on 2022-12-12 01:47

import cloudinary.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecismartAPP', '0004_delete_photos_registroaviso_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
            ],
        ),
        migrations.AlterField(
            model_name='registroaviso',
            name='Fecha_publicacion',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 12, 1, 47, 4, 344118, tzinfo=datetime.timezone.utc)),
        ),
    ]
