# Generated by Django 4.1.4 on 2022-12-09 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RecismartAPP', '0005_remove_registroaviso_imagen_imagenaviso_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagenaviso',
            old_name='Imagen',
            new_name='imagen',
        ),
        migrations.RenameField(
            model_name='imagenaviso',
            old_name='RegistroAviso',
            new_name='registroAviso',
        ),
    ]
