# Generated by Django 4.1.4 on 2022-12-09 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecismartAPP', '0006_rename_imagen_imagenaviso_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroaviso',
            name='Imagen',
            field=models.ImageField(blank=True, null=True, upload_to='publicacion'),
        ),
    ]
