# Generated by Django 4.1.4 on 2022-12-09 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RecismartAPP', '0007_alter_registroaviso_imagen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImagenAviso',
        ),
    ]
