# Generated by Django 4.1.4 on 2022-12-12 11:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecismartAPP', '0007_remove_registroaviso_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroaviso',
            name='Fecha_publicacion',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 12, 11, 42, 0, 966031, tzinfo=datetime.timezone.utc)),
        ),
    ]
