# Generated by Django 4.1.3 on 2022-12-13 12:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RecismartAPP', '0008_alter_registroaviso_fecha_publicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroaviso',
            name='imagen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RecismartAPP.fotos'),
        ),
        migrations.AlterField(
            model_name='registroaviso',
            name='Fecha_publicacion',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 13, 12, 20, 59, 213196, tzinfo=datetime.timezone.utc)),
        ),
    ]
