# Generated by Django 4.1.3 on 2022-12-10 01:20

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RecismartAPP', '0012_imageaviso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroaviso',
            name='Imagen',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Imagen'),
        ),
        migrations.DeleteModel(
            name='ImageAviso',
        ),
    ]
