# Generated by Django 4.1.3 on 2022-12-10 01:26

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RecismartAPP', '0013_alter_registroaviso_imagen_delete_imageaviso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroaviso',
            name='Imagen',
        ),
        migrations.CreateModel(
            name='ImageAviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255)),
                ('aviso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RecismartAPP.registroaviso')),
            ],
        ),
    ]
