# Generated by Django 4.1.3 on 2022-12-10 01:46

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RecismartAPP', '0014_remove_registroaviso_imagen_imageaviso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageaviso',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
