# Generated by Django 4.1.3 on 2022-12-10 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecismartAPP', '0015_alter_imageaviso_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroaviso',
            name='imagen',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
