# Generated by Django 4.1.3 on 2022-12-10 01:53

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RecismartAPP', '0016_registroaviso_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroaviso',
            name='imagen',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='imagen'),
        ),
        migrations.DeleteModel(
            name='ImageAviso',
        ),
    ]
