# Generated by Django 4.1.4 on 2022-12-11 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RecismartAPP', '0018_registropersonas_delete_cuentarecolector_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registropersonas',
            old_name='Email',
            new_name='mail',
        ),
    ]
