# Generated by Django 4.1.4 on 2022-12-11 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RecismartAPP', '0019_rename_email_registropersonas_mail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registropersonas',
            name='mail',
        ),
    ]
