# Generated by Django 4.1.4 on 2022-12-11 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecismartAPP', '0020_remove_registropersonas_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='registropersonas',
            name='Correo',
            field=models.EmailField(blank=True, max_length=100, unique=True),
        ),
    ]
