# Generated by Django 4.1.4 on 2022-12-11 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RecismartAPP', '0022_remove_registropersonas_correo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaRecolector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rut_Empresa', models.CharField(max_length=100, unique=True)),
                ('Nombre', models.CharField(max_length=50)),
                ('Apellido', models.CharField(max_length=50)),
                ('Correo_electronico', models.EmailField(max_length=50, unique=True)),
                ('Telefono', models.CharField(max_length=100)),
                ('Direccion', models.CharField(max_length=100)),
                ('Nombre_de_empresa', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CuentaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rut', models.CharField(max_length=100, unique=True)),
                ('Nombre', models.CharField(max_length=50)),
                ('Apellido', models.CharField(max_length=50)),
                ('Correo_electronico', models.EmailField(max_length=50, unique=True)),
                ('Telefono', models.CharField(max_length=100)),
                ('Direccion', models.CharField(max_length=100)),
                ('Comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RecismartAPP.comunas')),
                ('Region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RecismartAPP.regiones')),
            ],
        ),
        migrations.AlterField(
            model_name='registroaviso',
            name='Descripcion',
            field=models.TextField(max_length=500),
        ),
        migrations.DeleteModel(
            name='RegistroPersonas',
        ),
    ]
